theme: jekyll-theme-hacker
title: Xander Pendrake
description: The collected stories, interactive and otheriwise, of Xander Pendrake
excludes: README.md
url: https://xanderpendrake.github.io/
excerpt_separator: <!--more-->
